services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=kani
      - POSTGRES_DB=employee
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: