spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: kani
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

